// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtayvwttqsqzhivepemu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10YXl2d3R0cXNxemhpdmVwZW11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMDAzNjAsImV4cCI6MjA2NTg3NjM2MH0.C-dFZrHJG1PoHytI9FIKT1B0YF_a0j8t1PtPamdOPxs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);